name = "nexo-landing"
main = "index.js"
compatibility_date = "2026-08-04"
[site]
bucket = "./public"
entry-point = "workers-site"
account_id = "d4a41af7898b091e9b01b7f73bc00c6d"
workers_dev = true
[vars]
"assets": {
  "directory": "./public"
}




